name = "englishholidays"
compatibility_date = "2024-09-23"
main = "worker.mjs"
assets = { directory = "./public", binding = "ASSETS" }

secrets_store_secrets = [
  { binding = "calendarific", store_id = "fdfe90262239479a8209ce7ceef6103d", secret_name = "calendarific" }
]

[[kv_namespaces]]
binding = "HOLIDAY_DATA"
id = "f87daf29923048d69a3211ad7472b0fe"

[triggers]
crons = ["0 */4 * * *"]

[build]
command = "npm run populate-kv"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
